framework:
    secret: test_blah
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    default_locale: en
    trusted_proxies: ~
    session: ~
    test: ~
    
doctrine:
    dbal:
        driver:   pdo_sqlite
        host:     ""
        port:     ""
        dbname:   "%kernel.root_dir%/neducatio_testbundle.sqlite"
        path:     "%kernel.root_dir%/neducatio_testbundle.sqlite"
        user:     ""
        password: ""
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true